############# English navigation ##############

# main menu
[[main]]
name = "首頁"
url = "/"
weight = 1

[[main]]
name = "關於協會"
url = "/about"
weight = 2

[[main]]
name = "鍾肇政"
url = "/chung-chao-cheng"
weight = 3

[[main]]
weight = 4
name = "專文"
url = "/blog"

[[main]]
parent = "專文"      
name = "文章列表"         
url = "/blog"
weight = 1

[[main]]
parent = "專文"
name = "Categories"
url = "/categories"
weight = 2

[[main]]
weight = 5
# parent = "Pages"
name = "研究資源"
url = "/resources"

[[main]]
weight = 6
name = "授權合作"
url = "/licensing"

[[main]]
weight = 7
# parent = "Pages"
name = "聯絡協會"
url = "/contact"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "/404"

# footer menu
[[footer]]
name = "關於協會"
url = "/about"
weight = 1

[[footer]]
name = "授權合作"
url = "/licensing"
weight = 2

[[footer]]
name = "聯絡協會"
url = "/contact"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 4
